[pyprland]
plugins = [
  "magnify",
  "scratchpads"
]

[scratchpads.clock]
animation = "fromTop"
command = "kitty --class kitty-cl -e tty-clock -bcsDC7"
class = "kitty-cl"
size = "75% 16%"
max_size = "1920px 100%"
margin = 20

[scratchpads.bottom]
animation = "fromBottom"
command = "kitty --class kitty-ff"
class = "kitty-ff"
size = "75% 75%"
max_size = "1920px 100%"
margin = 50
