[pyprland]
plugins = [
  "magnify",
  "scratchpads"
]

[scratchpads.clock]
animation = "fromTop"
command = "kitty --class kitty-cl -e tty-clock -cC7"
class = "kitty-cl"
size = "75% 75%"
max_size = "1920px 100%"
margin = 50

[scratchpads.left]
animation = "fromLeft"
command = "kitty --class kitty-ff"
class = "kitty-ff"
size = "75% 75%"
max_size = "1920px 100%"
margin = 20

[scratchpads.music]
animation = "fromBottom"
command = "spotify --enable-features=UseOzonePlatform --ozone-platform=wayland"
class = "spotify"
size = "75% 75%"
max_size = "1920px 100%"
margin = 20
