[pyprland]
plugins = [
  "magnify",
  "scratchpads"
]

[scratchpads.top]
animation = "fromTop"
command = "kitty --class kitty-tp"
class = "kitty-tp"
size = "75% 90%"
max_size = "1920px 100%"
margin = 50

[scratchpads.bottom]
animation = "fromBottom"
command = "kitty --class kitty-bt"
class = "kitty-bt"
size = "75% 90%"
max_size = "1920px 100%"
margin = 50
